# Generated by Django 6.0.6 on 2026-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='+1 555-0100', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Software Engineer', max_length=100, verbose_name='Job Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Remote', 'Remote')], default='Active', max_length=20, verbose_name='Status'),
        ),
    ]
